from enum import IntEnum

class Technique(IntEnum): # IntEnum car chaque methodes humaine doit avoir son propre nombre de difficulte
    SINGLETON_NU = 1
    DERNIER_NOMBRE = 2
    SINGLETON_CACHE = 3 # le plus le chiffre est grand, le plus dur est-il le methode
    # PAIR_NU ...
    # PAIR_CACHE ...
    # ...